meta:
  engine: 4.1.0
  name: risha
  version: 0.4.0
  author: sboysel
  url: https://github.com/sboysel/risha

units:
  kx: U
  ky: U
  width: 102            # board max width
  px: 0.5kx - 2.5       # horizontal padding (main)
  py: 0.5ky             # vertical padding (main)
  tx: width - 5U + 5    # horizontal shift (thumbfan)
  ty: 0.3ky             # vertical shift (thumbfan)
  mcux: 4.5             # horizontal shift (MCU) 
  mcuy: 1.1ky           # vertical shift (MCU)
  trrsx: 0.85kx         # horizontal shift (TRRS jack)
  trrsy: py             # vertical shift (TRRS jack)

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -5ky]
      columns:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [tx, -1ky - ty]
      columns:
        near:
        far:
      rows:
        home:
  key:
    padding: 1ky
    spread: 1kx

outlines:
  risha:
    - what: polygon
      points:
        # NW
        - ref: matrix_pinky_top
          shift: [-px, py]
        # NE
        - ref: matrix_inner_top
          shift: [px + tx, py]
        # SE
        - ref: thumbfan_far_home
          shift: [px, -py]
        # SW
        - ref: matrix_pinky_bottom
          shift: [-px, -py - ty - 1ky]
      fillet: 2
    # MCU cutout
    - what: rectangle 
      where:
        ref: matrix_pinky_bottom
        shift: [0, -mcuy]
      size: [26.5, 12.5]
      operation: subtract


pcbs:
  risha:
    outlines:
      main:
        outline: risha
        footprints:
    footprints:
      mx:
        what: placeholder
        where: true
        params:
          designator: MX
          value: MX_SW_solder
          side: F
      rp2040_zero:
        what: placeholder
        where:
          ref: matrix_pinky_bottom
          shift: [mcux, -mcuy]
          rotate: 90
        params:
          designator: U
          value: RP2040-Matrix
          side: F
      trrs:
        what: placeholder
        where:
          ref: matrix_inner_top
          shift: [trrsx, trrsy]
          rotate: 270
        params:
          designator: J
          value: PJ-320A
          side: F
      jlc_text:
        what: text 
        where:
          ref: matrix_ring_home
          shift: [0.5kx, 0.5ky]
        params:
          text: 'JLCJLCJLCJLC'
      version_text_front:
        what: text 
        where:
          ref: matrix_ring_bottom
          shift: [0.5kx, 0.5ky]
        params:
          text: 'risha v0.4.0'
          side: F
          knockout: true
      version_text_back:
        what: text 
        where:
          ref: matrix_ring_bottom
          shift: [0.5kx, 0.5ky]
        params:
          text: 'risha v0.4.0'
          side: B
          knockout: true
          justify: mirror
